# Generated by Django 4.1.3 on 2022-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('SURNAME', models.CharField(max_length=50)),
            ],
        ),
    ]
