# Generated by Django 4.1.3 on 2022-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
