# Generated by Django 4.1.4 on 2022-12-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='Userid',
            field=models.CharField(default=int, max_length=50),
            preserve_default=False,
        ),
    ]
