# Generated by Django 4.1.4 on 2022-12-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_entry_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Userid',
            new_name='USERID',
        ),
    ]
